// Copyright Ironic Studio. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "Blueprint/WidgetChild.h"
#include "UIDataTypes.generated.h"

UENUM(BlueprintType)
enum class ERPGUILayer : uint8
{
    Menu,
    Modal,
    System,
    Num UMETA(Hidden)
};

/** How a navigation region generates its default directional links. */
UENUM(BlueprintType)
enum class ERPGNavigationRegionLayout : uint8
{
    Manual,
    VerticalList,
    HorizontalList,
    Grid
};

/** How a widget overrides one direction of the automatically generated navigation graph. */
UENUM(BlueprintType)
enum class ERPGNavigationRule : uint8
{
    /** Keep the link generated by the owning navigation region. */
    Auto,

    /** Replace the generated link with TargetNavigationId. */
    ExplicitTarget,

    /** Remove this direction completely. */
    Block,

    /** Ask the owning NavigationWidget Blueprint/C++ override at runtime. */
    Dynamic
};

USTRUCT(BlueprintType)
struct UIFRAMEWORK_API FRPGNavigationOverride
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Navigation")
    ERPGNavigationRule Rule = ERPGNavigationRule::Auto;

    /** Used when Rule is ExplicitTarget. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Navigation", meta=(EditCondition="Rule == ERPGNavigationRule::ExplicitTarget", EditConditionHides, DisplayName="Target Widget Name"))
    FName TargetNavigationId = NAME_None;

    /**
     * When true, this link is only allowed on a fresh direction press.
     * Use it for wrap-around links such as the right edge of a grid returning to its left edge.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Navigation")
    bool bRequireNewPress = false;
};

USTRUCT(BlueprintType)
struct UIFRAMEWORK_API FRPGNavigationOverrides
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Navigation")
    FRPGNavigationOverride Up;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Navigation")
    FRPGNavigationOverride Down;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Navigation")
    FRPGNavigationOverride Left;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Navigation")
    FRPGNavigationOverride Right;
};

/**
 * A serializable, authored navigation region.
 *
 * Static regions are resolved from the owning UUserWidget's WidgetTree whenever
 * UNavigationWidget rebuilds its graph. SourceWidget uses UMG's widget-child picker,
 * so designers can select the source panel instead of typing its name manually.
 */
USTRUCT(BlueprintType)
struct UIFRAMEWORK_API FRPGNavigationRegionDefinition
{
    GENERATED_BODY()

    /** Optional stable region id. When empty, the selected source widget name is used. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Navigation")
    FName RegionId = NAME_None;

    /**
     * Select a UMG Designer panel as this region's automatic-navigation source.
     * The selected widget must resolve to a UPanelWidget at runtime.
     */
    UPROPERTY(EditAnywhere, Category = "Navigation")
    FWidgetChild SourceWidget;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Navigation")
    ERPGNavigationRegionLayout Layout = ERPGNavigationRegionLayout::Manual;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Navigation")
    bool bAllowWrap = false;

    /** Marks generated wrap edges as requiring release before they can be used again. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Navigation")
    bool bRequireNewPressForWrap = true;
};

/**
 * A persistent, authored link. It is applied after auto-generation and per-widget overrides.
 *
 * SourceWidget and TargetWidget use UMG's widget-child picker. Their selected widget names are
 * also the graph ids, so no separate navigation-id field is required for authored links.
 */
USTRUCT(BlueprintType)
struct UIFRAMEWORK_API FRPGNavigationLink
{
    GENERATED_BODY()

    /** The interactive widget from which this directional link begins. */
    UPROPERTY(EditAnywhere, Category = "Navigation")
    FWidgetChild SourceWidget;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Navigation")
    EUINavigation Direction = EUINavigation::Down;

    /** The interactive widget to focus when this link is used. */
    UPROPERTY(EditAnywhere, Category = "Navigation")
    FWidgetChild TargetWidget;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Navigation")
    bool bRequireNewPress = false;

private:
    /*
     * Compatibility fallback for assets authored before SourceWidget / TargetWidget
     * became widget-child pickers. These fields are intentionally hidden from Details.
     * New links always use the selected widget names above as their graph ids.
     */
    UPROPERTY(meta=(DeprecatedProperty, DeprecationMessage="Use Source Widget instead."))
    FName SourceNavigationId = NAME_None;

    UPROPERTY(meta=(DeprecatedProperty, DeprecationMessage="Use Target Widget instead."))
    FName TargetNavigationId = NAME_None;

    friend class UNavigationWidget;
};

/** Context supplied whenever a page is created and pushed onto a UI stack. */
USTRUCT(BlueprintType)
struct UIFRAMEWORK_API FRPGUIOpenArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite)
    TObjectPtr<UObject> ContextObject = nullptr;

    UPROPERTY(BlueprintReadWrite)
    FGameplayTag ContextTag;

    UPROPERTY(BlueprintReadWrite)
    int32 Index = INDEX_NONE;

    UPROPERTY(BlueprintReadWrite)
    FName ContextName = NAME_None;

    UPROPERTY(BlueprintReadWrite)
    FText ContextText;
};
