;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Character.Event.Dead",NewTagName="Character.Event.Death")
+GameplayTagRedirects=(OldTagName="Character.Event.Death",NewTagName="Event.Event.Death")
+GameplayTagRedirects=(OldTagName="Character.Event.HitReact",NewTagName="Event.Event.HitReact")
+GameplayTagRedirects=(OldTagName="Character.Event",NewTagName="Event.Event")
+GameplayTagRedirects=(OldTagName="Character.State",NewTagName="Event.State")
+GameplayTagRedirects=(OldTagName="Character",NewTagName="Event")
+GameplayTagRedirects=(OldTagName="Event.Event.Death",NewTagName="Event.Combat.Death")
+GameplayTagRedirects=(OldTagName="Event.Event.HitReact",NewTagName="Event.Combat.HitReact")
+GameplayTagRedirects=(OldTagName="Event.Event",NewTagName="Event.Combat")
+GameplayTagRedirects=(OldTagName="Ability.Formula.Death",NewTagName="Ability.Effect.Death")
+GameplayTagRedirects=(OldTagName="Ability.Formula.Test",NewTagName="Ability.Effect.Test")
+GameplayTagRedirects=(OldTagName="Ability.Formula",NewTagName="Ability.Effect")
+GameplayTagList=(Tag="Ability.Cooldown.Test",DevComment="")
+GameplayTagList=(Tag="Ability.Cooldown.Test1",DevComment="")
+GameplayTagList=(Tag="Ability.Data.Damage",DevComment="")
+GameplayTagList=(Tag="Ability.Data.Heal",DevComment="")
+GameplayTagList=(Tag="Ability.Effect.Death",DevComment="")
+GameplayTagList=(Tag="Ability.Effect.Test",DevComment="")
+GameplayTagList=(Tag="Ability.Jump",DevComment="")
+GameplayTagList=(Tag="Anim",DevComment="")
+GameplayTagList=(Tag="Anim.Combat.Death",DevComment="")
+GameplayTagList=(Tag="Anim.Combat.HitReact.Light",DevComment="")
+GameplayTagList=(Tag="Anim.Combat.Test",DevComment="")
+GameplayTagList=(Tag="Character.State.ActivatingSkill",DevComment="")
+GameplayTagList=(Tag="Character.State.Dead",DevComment="")
+GameplayTagList=(Tag="Character.State.Dying",DevComment="")
+GameplayTagList=(Tag="Character.State.Reviving",DevComment="")
+GameplayTagList=(Tag="Effect.Type.Damage",DevComment="")
+GameplayTagList=(Tag="EntryPoint.Start",DevComment="")
+GameplayTagList=(Tag="EntryPoint.Test",DevComment="")
+GameplayTagList=(Tag="Event.Combat.Death",DevComment="")
+GameplayTagList=(Tag="Event.Combat.HitReact",DevComment="")
+GameplayTagList=(Tag="Event.Combat.Revive",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Light",DevComment="")
+GameplayTagList=(Tag="Team.Ally",DevComment="")
+GameplayTagList=(Tag="Team.Enemy",DevComment="")
+GameplayTagList=(Tag="Team.Neutral",DevComment="")

